const option = [
    { label: "Acrobatics", value: "Acrobatics" },
    { label: "Aerobic Gymnastics", value: "Aerobic Gymnastics" },
    { label: "Archery", value: "Archery" },
    { label: "Arnis", value: "Arnis" },
    { label: "Artistic Gymnastics", value: "Artistic Gymnastics" },
    { label: "Artistic Swimming", value: "Artistic Swimming" },
    { label: "Badminton", value: "Badminton" },
    { label: "Baseball", value: "Baseball" },
    { label: "Basketball", value: "Basketball" },
    { label: "Baton Twirling", value: "Baton Twirling" },
    { label: "Bicycle Motocross (BMX)", value: "Bicycle Motocross (BMX)" },
    { label: "Billiards/ Pool (U.S.)", value: "Billiards/ Pool (U.S.)" },
    { label: "Bobsleigh", value: "Bobsleigh" },
    { label: "Bodybuilding", value: "Bodybuilding" },
    { label: "Bowling", value: "Bowling" },
    { label: "Boxing", value: "Boxing" },
    { label: "Canoeing", value: "Canoeing" },
    { label: "Car Racing", value: "Car Racing" },
    { label: "Cheerleading", value: "Cheerleading" },
    { label: "Chess", value: "Chess" },
    { label: "Cricket", value: "Cricket" },
    { label: "Croquet", value: "Croquet" },
    { label: "Curling", value: "Curling" },
    { label: "Dance Sport", value: "Dance Sport" },
    { label: "Darts", value: "Darts" },
    { label: "Diving", value: "Diving" },
    { label: "Dodgeball", value: "Dodgeball" },
    { label: "Fencing", value: "Fencing" },
    { label: "Figure Skating", value: "Figure Skating" },
    { label: "Football", value: "Football" },
    { label: "Frisbee", value: "Frisbee" },
    { label: "Golf", value: "Golf" },
    { label: "Handball", value: "Handball" },
    { label: "Hang Gliding", value: "Hang Gliding" },
    { label: "Hockey", value: "Hockey" },
    { label: "Horseback Riding", value: "Horseback Riding" },
    { label: "Horse Racing", value: "Horse Racing" },
    { label: "Ice Hockey", value: "Ice Hockey" },
    { label: "Ice Skating", value: "Ice Skating" },
    { label: "Jet Ski Racing", value: "Jet Ski Racing" },
    { label: "Judo", value: "Judo" },
    { label: "Karate", value: "Karate" },
    { label: "Kayaking", value: "Kayaking" },
    { label: "Kendo", value: "Kendo" },
    { label: "Kick Boxing", value: "Kick Boxing" },
    { label: "Kite Surfing", value: "Kite Surfing" },
    { label: "Lacrosse", value: "Lacrosse" },
    { label: "Luge", value: "Luge" },
    { label: "Mixed Martial Arts", value: "Mixed Martial Arts" },
    { label: "Motocross", value: "Motocross" },
    { label: "Muay Thai", value: "Muay Thai" },
    { label: "Paintball", value: "Paintball" },
    { label: "Parachuting", value: "Parachuting" },
    { label: "Paragliding", value: "Paragliding" },
    { label: "Parkour", value: "Parkour" },
    { label: "Polo", value: "Polo" },
    { label: "Pool/Billiards", value: "Pool/Billiards" },
    { label: "Powerlifting", value: "Powerlifting" },
    { label: "Rafting", value: "Rafting" },
    { label: "Rhythmic Gymnastics", value: "Rhythmic Gymnastics" },
    { label: "Rock Climbing", value: "Rock Climbing" },
    { label: "Rowing", value: "Rowing" },
    { label: "Rugby", value: "Rugby" },
    { label: "Sailing", value: "Sailing" },
    { label: "Sandboarding", value: "Sandboarding" },
    { label: "Scuba Diving", value: "Scuba Diving" },
    { label: "Shooting", value: "Shooting" },
    { label: "Skateboarding", value: "Skateboarding" },
    { label: "Skeleton", value: "Skeleton" },
    { label: "Skiing", value: "Skiing" },
    { label: "Snowboarding", value: "Snowboarding" },
    { label: "Softball", value: "Softball" },
    { label: "Speed Skating", value: "Speed Skating" },
    { label: "Sport Climbing", value: "Sport Climbing" },
    { label: "Squash", value: "Squash" },
    { label: "Sumo Wrestling", value: "Sumo Wrestling" },
    { label: "Surfing", value: "Surfing" },
    { label: "Swimming", value: "Swimming" },
    { label: "Synchronized Skating", value: "Synchronized Skating" },
    { label: "Synchronized Swimming", value: "Synchronized Swimming" },
    { label: "Table Tennis", value: "Table Tennis" },
    { label: "Taekwondo", value: "Taekwondo" },
    { label: "Tennis", value: "Tennis" },
    { label: "Track and Field", value: "Track and Field" },
    { label: "Trampolining", value: "Trampolining" },
    { label: "Triathlon (Tetrathlon, etc.)", value: "Triathlon (Tetrathlon, etc.)" },
    { label: "Tug of War", value: "Tug of War" },
    { label: "Volleyball", value: "Volleyball" },
    { label: "Water Polo", value: "Water Polo" },
    { label: "Weightlifting", value: "Weightlifting" },
    { label: "Windsurfing", value: "Windsurfing" },
    { label: "Wrestling", value: "Wrestling" },
    { label: "Wu Shu", value: "Wu Shu" },
]

export { option }